# Generated by Django 6.0 on 2025-12-19 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.planttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
