# Generated by Django 6.0 on 2025-12-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantTypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plants.planttype')),
            ],
        ),
    ]
