# Generated by Django 6.0 on 2025-12-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=100)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantings.planting')),
            ],
        ),
    ]
